# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Block_design/Block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design || ORIG_REF_NAME==Block_design} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_processing_system7_0_0/Block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_processing_system7_0_0 || ORIG_REF_NAME==Block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_doHist_0_0/Block_design_doHist_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_doHist_0_0 || ORIG_REF_NAME==Block_design_doHist_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_doHistStrech_0_0/Block_design_doHistStrech_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_doHistStrech_0_0 || ORIG_REF_NAME==Block_design_doHistStrech_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_axi_dma_0_0/Block_design_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_axi_dma_0_0 || ORIG_REF_NAME==Block_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_axi_smc_0/Block_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_axi_smc_0 || ORIG_REF_NAME==Block_design_axi_smc_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_rst_ps7_0_100M_0/Block_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Block_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_xbar_0/Block_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_xbar_0 || ORIG_REF_NAME==Block_design_xbar_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_ps7_0_axi_periph_0/Block_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_axis_broadcaster_0_0/Block_design_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_axis_broadcaster_0_0 || ORIG_REF_NAME==Block_design_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_doHist_0_bram_0/Block_design_doHist_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_doHist_0_bram_0 || ORIG_REF_NAME==Block_design_doHist_0_bram_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_axi_bram_ctrl_0_0/Block_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Block_design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_auto_pc_3/Block_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_auto_pc_3 || ORIG_REF_NAME==Block_design_auto_pc_3} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_auto_pc_0/Block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_auto_pc_0 || ORIG_REF_NAME==Block_design_auto_pc_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_auto_pc_1/Block_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_auto_pc_1 || ORIG_REF_NAME==Block_design_auto_pc_1} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_auto_pc_2/Block_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_auto_pc_2 || ORIG_REF_NAME==Block_design_auto_pc_2} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_system_ila_0_0/Block_design_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_design_system_ila_0_0 || ORIG_REF_NAME==Block_design_system_ila_0_0} -quiet] -quiet

# XDC: bd/Block_design/Block_design_ooc.xdc
